name: hamil_sehat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.2
  get: 4.6.5
  get_storage: 2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: 2.0.11
  audioplayers: 1.2.0
  device_preview: ^1.1.0
  youtube_player_flutter: ^8.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lg0.png"
  min_sdk_android: 21


flutter: 
  assets: 
    - assets/images/
    - assets/music/
  uses-material-design: true

